# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsm < Formula
  desc "Native Golang CLI tool for managing AWS SSM sessions"
  homepage "https://github.com/johnlam90/aws-ssm"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnlam90/aws-ssm/releases/download/v0.1.0/aws-ssm-darwin-amd64.tar.gz"
      sha256 "11ed1020a7b98106a1c0702f486dbbcd119214063253bd9dac99b33f422fbe86"

      def install
        bin.install "aws-ssm-darwin-amd64" => "aws-ssm"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/johnlam90/aws-ssm/releases/download/v0.1.0/aws-ssm-darwin-arm64.tar.gz"
      sha256 "2abb8deefb8c5d5086afb2d5d8994f06757e89fe08ddab6b9d3d6ab792c1a64e"

      def install
        bin.install "aws-ssm-darwin-arm64" => "aws-ssm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/johnlam90/aws-ssm/releases/download/v0.1.0/aws-ssm-linux-amd64.tar.gz"
      sha256 "a46920a62e90c94849ffcb7cc176fcc58e2f9ffdd2d2813846a31658f8aa031d"

      def install
        bin.install "aws-ssm-linux-amd64" => "aws-ssm"
      end
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnlam90/aws-ssm/releases/download/v0.1.0/aws-ssm-linux-arm64.tar.gz"
      sha256 "5e0a7a6f72fd5679bc124821244a9650b0b742feb2f30b5271a90cfb978c7d75"

      def install
        bin.install "aws-ssm-linux-arm64" => "aws-ssm"
      end
    end
  end

  test do
    system "#{bin}/aws-ssm", "version"
  end
end

